@startuml 業務フロー

partition ファシリテーター {
  (*) --> "テーブル準備"
  --> "テーブルに招待する"
  -[hidden]-> "テーブルのカードを開示する"
  "テーブルのカードを開示する" --> "テーブルを空にする"
  "テーブルのカードを開示する" --> "テーブルを解散する"
  "テーブルを解散する" --> (*)
}
partition プレイヤー {
  "テーブルに招待する" -r-> "テーブル参加"
  --> "テーブルにカードを伏せる"
  --> "テーブルのカードを交換する"
  -u-> "テーブルにカードを伏せる"
}
partition ファシリテーター {
  "テーブルにカードを伏せる" -l-> "テーブルのカードを開示する"
  "テーブルを空にする" -u-> "テーブルにカードを伏せる"
}
@enduml
